spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mysql://1.116.157.121:3306/xcplus_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: Zyj19981234567.
    driver-class-name: com.mysql.cj.jdbc.Driver
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


