### 创建课程
POST http://localhost:63040/content/course
Content-Type: application/json

{
  "charge": "",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "",
  "tags": "",
  "grade": "204001",
  "description": "",
  "objectives": ""
}